apiVersion: v1
kind: Service
metadata:
  name: grafana-main
  namespace: grafana
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30901
    port: 3000
    protocol: TCP
    targetPort: grafana-http
  selector:
    app: grafana
